[develop] Carlos - Mapper and Common assertion steps
AWT-05/trello-api-tests pull request #11
Opened 2020-05-11 19:06 UTC by carlosmc23

2020-05-11 19:32 UTC, marcos-x86 requested changes

2020-05-11 19:32 UTC, marcos-x86 commented on src/test/resources/features/boards/CRUD_Examples.feature
> +    Then I validate the response has status code 200
Please consider adding an empty line at the end of the file.

2020-05-11 19:32 UTC, marcos-x86 commented on src/main/java/org/fundacionjala/trello/config/IRequestManager.java
> +    void verifyJsonSchema(Response response, String schemaPath);
Please consider moving the Jsonschema validation method to another utility class. To my understanding Request Manager should only be in charge of sending requests. You can create a class of JsonSchemaUtils (for example) and move the schema validation methods there, remember that JSON schema validator is a different library than Rest Assured.

2020-05-11 19:32 UTC, marcos-x86 commented on src/test/java/org/fundacionjala/trello/stepdefs/RequestSteps.java
> +    @And("I save response as {string}")
Please consider changing this annotation to `When`.

2020-05-11 19:32 UTC, marcos-x86 commented on src/test/java/org/fundacionjala/trello/stepdefs/RequestSteps.java
> +    @And("I validate the response body should match with {string} JSON schema")
Please consider changing this annotation to `Then`.

2020-05-11 19:32 UTC, marcos-x86 commented on src/test/java/org/fundacionjala/trello/stepdefs/RequestSteps.java
> +    @And("I validate the response contains the following data")
Please consider changing this annotation to `Then`. And cleanup unused imports.

2020-05-11 19:32 UTC, marcos-x86 commented on src/test/resources/features/boards/CRUD_Examples.feature
> +
Please consider deleting this empty line.

2020-05-11 19:35 UTC, luqp reviewed
Take care ;)

2020-05-11 19:35 UTC, luqp commented on src/main/java/org/fundacionjala/trello/config/IRequestManager.java
> +    void verifyJsonSchema(Response response, String schemaPath);
I believe this method has a different responsibility than the RequestManager does (Give an easy way to send requests).
I suggest you put it in a new  class  call CommonValidation.

2020-05-11 19:35 UTC, luqp commented on src/main/java/org/fundacionjala/trello/config/RequestManagerRestAssured.java
> +    public void verifyJsonSchema(final Response response, final String schemaPath) {
I believe this method has a different responsibility than the RequestManager does (Give an easy way to send requests).
I suggest you put it in a new class call CommonValidation.

2020-05-11 19:56 UTC, carlosmc23 commented on src/test/resources/features/boards/CRUD_Examples.feature
> +    Then I validate the response has status code 200
ok

2020-05-12 03:11 UTC, luqp reviewed
Good job, I leave some comments please take a look.

2020-05-12 03:11 UTC, luqp commented on src/main/java/org/fundacionjala/trello/config/RequestManagerRestAssured.java
> +    private static final String SCHEMAS_BASE_FOLDER = "src/test/resources/schemas/";
I suggest clean it, because this constant is not being used.

2020-05-12 03:11 UTC, luqp commented on src/test/java/org/fundacionjala/trello/stepdefs/RequestSteps.java
> +     *
I believe that "H" is missing in this javadoc

2020-05-12 03:11 UTC, luqp commented on src/test/java/org/fundacionjala/trello/stepdefs/RequestSteps.java
> +     * Validates response status code.
I think that we can split the **request methods** and **validate methods** in different class to apply the single responsibility.
But this only a suggestion.

2020-05-12 03:11 UTC, luqp commented on src/test/resources/features/boards/CRUD_Examples.feature
> +      | name | new_test_trello_api_board |
In the future you can change background steps to **declarative**

2020-05-12 12:09 UTC, marcos-x86 commented
@carlosmc23 Please considering updating your branch according to the latest code merged and solve the comments that Lucero leaves. Consider the split oft the request step definitions and validation step definitions in different classes as optional.

2020-05-12 12:13 UTC, carlosmc23 commented on src/main/java/org/fundacionjala/trello/config/RequestManagerRestAssured.java
> +    private static final String SCHEMAS_BASE_FOLDER = "src/test/resources/schemas/";
ok, sorry I forgot clean that

2020-05-12 12:14 UTC, carlosmc23 commented on src/test/java/org/fundacionjala/trello/stepdefs/RequestSteps.java
> +     *
OK, S is missing the word is saves jeje

2020-05-12 12:22 UTC, carlosmc23 commented on src/test/java/org/fundacionjala/trello/stepdefs/RequestSteps.java
> +     * Validates response status code.
I think about that as common steps, but we can talk about that on skype

2020-05-12 12:26 UTC, carlosmc23 commented on src/test/resources/features/boards/CRUD_Examples.feature
> +      | name | new_test_trello_api_board |
Yes, we talked about it yesterday in class, but this is just an example, thanks

2020-05-12 12:51 UTC, marcos-x86 approved these changes

2020-05-12 12:51 UTC, merged