[develop] Carlos - deleteOrganization hooks and validationSteps for common validations
AWT-05/trello-api-tests pull request #22
Opened 2020-05-12 20:51 UTC by carlosmc23

2020-05-12 21:50 UTC, marcos-x86 requested changes

2020-05-12 21:50 UTC, marcos-x86 commented on src/test/java/org/fundacionjala/trello/stepdefs/RequestSteps.java
> +    @And("I save the id value to clean {string} workspace")
Please consider using the `@When` annotation.

2020-05-13 03:08 UTC, luqp reviewed
Good job, I leaved some comments, please take a look

2020-05-13 03:08 UTC, luqp commented on src/main/java/org/fundacionjala/trello/context/Context.java
> +    }
This is fine, but I would like we continue thinking in a way to refactor this part in the future.

2020-05-13 03:08 UTC, luqp commented on src/test/java/org/fundacionjala/trello/stepdefs/RequestSteps.java
> +    private static final String JSON_PATH_STRING_ID = "id";
I believe this name is too large, I suggest you change it for a shorted as "FIELD_ID" or "ID_KEY".

2020-05-13 03:08 UTC, luqp commented on src/test/java/org/fundacionjala/trello/stepdefs/RequestSteps.java
>       *
this javadoc looks good, but I would like to change for:
Saves the instance id in the context.

2020-05-13 03:08 UTC, luqp commented on src/test/java/org/fundacionjala/trello/stepdefs/ValidationSteps.java
> +     *
Update javadoc, because the class is **ValidationSteps**

2020-05-13 03:08 UTC, luqp commented on src/test/java/org/fundacionjala/trello/stepdefs/ValidationSteps.java
> +        JsonSchemaUtils.verifyJsonSchema(context.getResponse(), schemaPath);
The method name is too late, I suggest you change for a shorted as "validateResponseBodyWithJSONSchema"

2020-05-13 03:08 UTC, luqp commented on src/test/java/org/fundacionjala/trello/stepdefs/ValidationSteps.java
> +    public void iValidateTheResponseContainsTheFollowingData(final Map<String, String> data) {
You can improve the methods names.

2020-05-13 04:05 UTC, Snip-77 requested changes

2020-05-13 04:05 UTC, Snip-77 commented on src/test/java/org/fundacionjala/trello/utils/JsonSchemaUtils.java
> +
This space is not needed.

2020-05-13 04:05 UTC, Snip-77 commented on src/test/java/org/fundacionjala/trello/utils/JsonSchemaUtils.java
> +     * @param response  response.
Maybe this could be a little more descriptive... 
@param response  class that contains the response from HTTP method. (in line 25 also)

2020-05-13 13:09 UTC, Snip-77 approved these changes

2020-05-13 14:27 UTC, marcos-x86 approved these changes

2020-05-13 14:27 UTC, merged